name: process-corpus
on:
  repository_dispatch:
    types:
      - webhook
  # schedule:
  #   - cron: "57 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.js
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.28.x
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Fetch data
        uses: githubocto/flat@v3
        env:
          notification_url: ${{ secrets.CORPUS_NOTIFICATION_URL }}
        with:
          http_url: https://query.wikidata.org/sparql?format=json&query=SELECT%20DISTINCT%20%3Fitem%20%3FitemLabel%20%3Flicense%20%3FlicenseLabel%0AWHERE%20%7B%20%0A%20%20%3Fitem%20wdt%3AP6104%20wd%3AQ56241615%20.%20%0A%20%20%3Fitem%20wdt%3AP31%20wd%3AQ13442814%20.%0A%20%20%3Fitem%20wdt%3AP275%20%3Flicense%20.%0A%20%20%3Flicense%20wdt%3AP31*%2Fwdt%3AP279*%20wd%3AQ30939938%20.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D%0AGROUP%20BY%20%3Fitem%20%3FitemLabel%20%3Flicense%20%3FlicenseLabel
          downloaded_filename: ./corpus/entries.json
          postprocess: ./postprocess.js -f
